<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Registrasi Gagal</name>
   <tag></tag>
   <elementGuidId>23199891-ce0e-45ef-894b-1b2156e6a607</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#toast-2-description</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(text(), 'Registrasi Gagal')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8e10244a-0428-458d-b932-3d73c51823b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-status</name>
      <type>Main</type>
      <value>error</value>
      <webElementGuid>7cd14ea8-7d06-4a30-86cb-c2e1551f729c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>toast-2-description</value>
      <webElementGuid>35c6183f-e0af-4043-a193-b65f47b25ad1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-alert__desc css-161kwbg</value>
      <webElementGuid>a8dfa4e6-fbf3-4226-ba59-2fe5c1e089e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Registrasi Gagal</value>
      <webElementGuid>75dab4f9-d1da-44c8-8579-9648fb23b345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toast-2-description&quot;)</value>
      <webElementGuid>dc22d8a9-c198-4d13-a002-914c58a38693</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[contains(text(), 'Registrasi Gagal')]</value>
      <webElementGuid>66dfd433-14e0-4a47-a78f-8e828c74b5de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Instagram'])[1]/following::div[5]</value>
      <webElementGuid>85a71b92-c86f-478f-8359-cb70b1a57b9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YouTube'])[1]/following::div[5]</value>
      <webElementGuid>d564a6d5-a2cf-4ebe-abc6-35f70bbd3a7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'toast-2-description', '&quot;', ')')])[1]/preceding::div[1]</value>
      <webElementGuid>f5883524-a7af-4092-8e71-76543a7ee150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Registrasi Gagal']/parent::*</value>
      <webElementGuid>cf81e6d4-b1f8-4922-ab33-6c31c10b9bf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div</value>
      <webElementGuid>55ec0086-3fce-44c3-9620-c874627f6976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'toast-2-description' and (text() = 'Registrasi Gagal' or . = 'Registrasi Gagal')]</value>
      <webElementGuid>3ef915e9-44d2-4648-8650-051a455f15ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
