<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Cannot read properties of undefined (re_e4e67f</name>
   <tag></tag>
   <elementGuidId>c517136b-4102-4b3a-bc2f-5042c0f610f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#toast-2-description</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='toast-2-description']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>03dd9868-e64c-4c2d-a3f4-d5166af23a52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-status</name>
      <type>Main</type>
      <value>error</value>
      <webElementGuid>c9297f36-8f96-4866-a6b6-11294cad5766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>toast-2-description</value>
      <webElementGuid>bbd57eb6-98f1-4083-8040-d8471e1953c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-alert__desc css-161kwbg</value>
      <webElementGuid>5d2eba87-451b-4b24-bef3-ed2d7e09fd5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cannot read properties of undefined (reading '0')</value>
      <webElementGuid>d5aa5a77-e610-44ed-9d17-4100124df929</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toast-2-description&quot;)</value>
      <webElementGuid>f61eda34-028b-4d7c-b1be-04f8c0eb4a98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='toast-2-description']</value>
      <webElementGuid>0c1ec67e-2554-4e02-9ec0-7d1e4d4b40c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='toast-2']/div/div</value>
      <webElementGuid>48ba5aae-afa2-42ba-9b21-cfe62748dbb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Instagram'])[1]/following::div[5]</value>
      <webElementGuid>cecf1a31-53f2-40bd-b0a0-fdd2d7c36d5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YouTube'])[1]/following::div[5]</value>
      <webElementGuid>7e5a1c27-7389-4a2b-a6c4-1cd98cad2833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'toast-2-description', '&quot;', ')')])[1]/preceding::div[1]</value>
      <webElementGuid>39fdd3cd-a400-4584-81ef-57dc524db47f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/div/div</value>
      <webElementGuid>69c8e30b-3942-4731-88ad-eaf66a86b90c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'toast-2-description' and (text() = concat(&quot;Cannot read properties of undefined (reading &quot; , &quot;'&quot; , &quot;0&quot; , &quot;'&quot; , &quot;)&quot;) or . = concat(&quot;Cannot read properties of undefined (reading &quot; , &quot;'&quot; , &quot;0&quot; , &quot;'&quot; , &quot;)&quot;))]</value>
      <webElementGuid>a98c8ad3-ad34-477a-b458-3e4a5a9f49fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
