<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Edit Profil Berhasil</name>
   <tag></tag>
   <elementGuidId>0bac1e91-b4a4-447a-b86e-7fd5272c25ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#toast-2-description</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(text(), 'Edit Profile Berhasil')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fa2949cd-9cc9-43fe-9326-2eb011340b8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-status</name>
      <type>Main</type>
      <value>success</value>
      <webElementGuid>de363e7b-a562-4a0d-8db0-456765395144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>toast-2-description</value>
      <webElementGuid>1f9aa11a-bef1-4358-91f2-04ac67947b96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-alert__desc css-161kwbg</value>
      <webElementGuid>c7db32e8-35d9-482c-997a-f89c1c97e522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login Berhasil</value>
      <webElementGuid>96d27105-4800-4a2d-9bf7-a4155a52c7b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toast-2-description&quot;)</value>
      <webElementGuid>29e8ebb5-7a4f-42ce-86e7-8bb6c14d0185</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[contains(text(), 'Edit Profile Berhasil')]</value>
      <webElementGuid>981d78ae-59f1-4fcd-bac2-413490e56d17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='toast-2']/div/div</value>
      <webElementGuid>a8ce8b4b-bda0-4a52-9c68-316662aaaa27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Instagram'])[1]/following::div[5]</value>
      <webElementGuid>a3c9f131-3d93-4424-9cc2-4475ef1be78d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YouTube'])[1]/following::div[5]</value>
      <webElementGuid>55ea9f6e-44bc-4a24-aecb-77c75a210a3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'toast-2-description', '&quot;', ')')])[1]/preceding::div[1]</value>
      <webElementGuid>50ea4f2f-b0c0-4122-ae87-5c4271892b49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login Berhasil']/parent::*</value>
      <webElementGuid>3625fac8-2bca-47f2-96cf-51fc8be13a3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/div/div</value>
      <webElementGuid>2c2e2644-70e1-4328-8457-2d28f6668b4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'toast-2-description' and (text() = 'Edit Profile Berhasil' or . = 'Edit Profile Berhasil')]</value>
      <webElementGuid>57b7bb3c-fe22-4e05-8c56-a2540518b2e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
