<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Produk berhasil ditambahkan</name>
   <tag></tag>
   <elementGuidId>ef3614ed-476a-4514-b5b6-d81740f68313</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#toast-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='toast-3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a043cd09-5f5a-45c5-bf2f-bf19a138e671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-status</name>
      <type>Main</type>
      <value>success</value>
      <webElementGuid>82f11abb-61b8-466c-b0d9-72c492e24552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>toast-3</value>
      <webElementGuid>1753a2a4-356b-4dae-9269-8c92d64c340a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-alert css-qret8q</value>
      <webElementGuid>2f59ede3-f156-4d46-90e1-d6c58b7fdebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kaos Hitam Polos x1 berhasil ditambahkan ke keranjang</value>
      <webElementGuid>2726ba98-643e-48d8-b146-8453e83d6b8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toast-3&quot;)</value>
      <webElementGuid>3ab7a695-35de-4877-87f6-3b3bb6b64635</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='toast-3']</value>
      <webElementGuid>687d5662-2c03-4236-8c9d-3e7687effce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='chakra-toast-manager-bottom']/li/div/div</value>
      <webElementGuid>e83d870e-9050-4a2a-893b-634f204c9554</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Instagram'])[1]/following::div[3]</value>
      <webElementGuid>bfbcef52-e6cc-4dc4-966d-2a9d64499a47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YouTube'])[1]/following::div[3]</value>
      <webElementGuid>88ddb899-3632-4f73-be44-a7936cfb59f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'toast-3', '&quot;', ')')])[1]/preceding::div[3]</value>
      <webElementGuid>adaf949f-f53b-49f6-812f-8c35b3f3900f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div</value>
      <webElementGuid>d5349d50-3868-4d99-bc5c-4e814bd1e130</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'toast-3' and (text() = 'Produk berhasil ditambahkan ke keranjang' or . = 'Produk berhasil ditambahkan ke keranjang')]</value>
      <webElementGuid>96d58877-bfc8-422e-8ff9-a329df43e5a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
