<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Produk berhasil ditambahkan</name>
   <tag></tag>
   <elementGuidId>ef3614ed-476a-4514-b5b6-d81740f68313</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#toast-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(text(), 'Produk berhasil ditambahkan')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0dfb6526-57fe-40b3-a7d1-27b79a435e85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-status</name>
      <type>Main</type>
      <value>success</value>
      <webElementGuid>a63c8cb9-1a4a-4279-920b-af606773e1e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>toast-3</value>
      <webElementGuid>6dd69bc5-7844-4efb-a554-5e3881696113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-alert css-qret8q</value>
      <webElementGuid>2b0e85aa-18c1-4f2f-bd8e-949649313c8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kaos Hitam Polos x1 berhasil ditambahkan ke keranjang</value>
      <webElementGuid>1843da90-a902-4af0-90c4-d927fd04f400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toast-3&quot;)</value>
      <webElementGuid>a53be67d-dbd0-41b1-a1cd-27d7f030d530</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[contains(text(), 'Produk berhasil ditambahkan')]</value>
      <webElementGuid>af29b1da-b2f2-434c-bd65-6f05302002fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[contains(text(), 'Produk berhasil ditambahkan')]/li/div/div</value>
      <webElementGuid>f01e1de0-b05f-4333-b621-384392d4d610</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Instagram'])[1]/following::div[3]</value>
      <webElementGuid>9775a924-a84e-4b99-b3ed-8acaaec2136e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YouTube'])[1]/following::div[3]</value>
      <webElementGuid>27b2e405-f39c-4dbc-8875-4da97aaf812f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'toast-3', '&quot;', ')')])[1]/preceding::div[3]</value>
      <webElementGuid>6ea79102-0986-4b05-a933-1931971f4ce0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div</value>
      <webElementGuid>74378c5a-d701-44f3-82ab-d96f5241f6b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'toast-3' and (text() = 'Produk berhasil ditambahkan ke keranjang' or . = 'Produk berhasil ditambahkan ke keranjang')]</value>
      <webElementGuid>fb968c94-9b14-4f3f-9b17-ac847a2abce8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
