<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_batalkan pesanan berhasil</name>
   <tag></tag>
   <elementGuidId>099500d8-df1f-49a1-a7e7-d83c43f23f4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(text(), 'Status akan diupdate dalam beberapa saat']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#toast-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c1d4d781-1a5b-4e97-bccc-5530ceeaba1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-status</name>
      <type>Main</type>
      <value>success</value>
      <webElementGuid>4df6f403-c755-46b6-b578-1483eac2c998</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>toast-3</value>
      <webElementGuid>e10debf7-442c-4a98-895e-bc0d65bf49b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-alert css-qret8q</value>
      <webElementGuid>cc4728d7-3637-4177-85a4-976957e1edf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pesanan 64a41be719adf15178b42d75 dibatalkanStatus akan diupdate dalam beberapa saat</value>
      <webElementGuid>4fee0c17-8a38-48fb-8720-ba9dd941e66e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toast-3&quot;)</value>
      <webElementGuid>e437966e-c2da-4d90-97dc-55bca8683edc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[contains(text(), 'Status akan diupdate dalam beberapa saat']</value>
      <webElementGuid>694a655f-dc21-4058-8fc0-fd85c9c119da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='chakra-toast-manager-bottom']/li/div/div</value>
      <webElementGuid>7323863c-476a-4540-8354-799fb4c4486f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Instagram'])[1]/following::div[3]</value>
      <webElementGuid>68692799-9f36-421d-9db8-28917521946b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YouTube'])[1]/following::div[3]</value>
      <webElementGuid>a07ad59b-01ca-4945-8275-ffa219e47a5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div</value>
      <webElementGuid>908609b3-0970-4fea-8d38-267137cc5253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'toast-3' and (text() = 'Pesanan 64a41be719adf15178b42d75 dibatalkanStatus akan diupdate dalam beberapa saat' or . = 'Pesanan 64a41be719adf15178b42d75 dibatalkanStatus akan diupdate dalam beberapa saat')]</value>
      <webElementGuid>5870b969-f606-49f1-8fbd-75031425852b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
