<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Silahkan login terlebih dahulu (div)</name>
   <tag></tag>
   <elementGuidId>ca0cf14c-bdfe-47df-9620-7fd84fb45b82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#toast-4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='toast-4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>56170afb-e403-44ca-ac80-365c9167773c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-status</name>
      <type>Main</type>
      <value>warning</value>
      <webElementGuid>4d66aef8-4d28-4b9d-925a-804d15621cad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>toast-4</value>
      <webElementGuid>40fa3f55-fcc9-413a-87a0-3448a2acab81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-alert css-zqqgfp</value>
      <webElementGuid>74ead51b-9001-441f-b5c3-e9eb6b19932d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Silahkan login terlebih dahulu</value>
      <webElementGuid>2e91b841-fbe6-471d-ba14-6780c73024bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toast-4&quot;)</value>
      <webElementGuid>fdc652fe-739a-4781-8082-c9ff6c826b0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='toast-4']</value>
      <webElementGuid>9ae11333-6fb1-43a2-b663-85aed81f5d2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='chakra-toast-manager-bottom']/li/div/div</value>
      <webElementGuid>01f6bcd0-c15d-4665-9ad1-5e45084f139d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Instagram'])[1]/following::div[3]</value>
      <webElementGuid>2f6f0d86-ec6e-4c01-b3e9-299d2a4fa267</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YouTube'])[1]/following::div[3]</value>
      <webElementGuid>1cb39fea-fc4d-4f73-8142-47436e6e6046</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'toast-4', '&quot;', ')')])[1]/preceding::div[3]</value>
      <webElementGuid>c09acbaf-3b4f-4001-b77b-41070131bd14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div</value>
      <webElementGuid>38e500d7-7246-45f4-a1ae-1bb587b59c26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'toast-4' and (text() = 'Silahkan login terlebih dahulu' or . = 'Silahkan login terlebih dahulu')]</value>
      <webElementGuid>e0e33d2c-03a5-41a6-ab30-abdf26c2be9c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
