<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Batalkan</name>
   <tag></tag>
   <elementGuidId>a20d1f88-415d-4885-980d-3091676c407b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cancel-order-button-23</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='cancel-order-button-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d49e063e-fc6a-49e9-90dc-0369bc8766b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1d08b0c7-e072-4bdf-9a9f-dfaea38af7a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-button css-1juyv81</value>
      <webElementGuid>81432183-795a-4b9e-9006-2835d14bd464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cancel-order-button-23</value>
      <webElementGuid>4fe87270-e37b-4a35-b167-f511623afd38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Batalkan</value>
      <webElementGuid>cd616dfb-43eb-4546-a525-b686e25c7796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cancel-order-button-23&quot;)</value>
      <webElementGuid>415f8225-1c75-4477-9e8f-a200861debaf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='cancel-order-button-1']</value>
      <webElementGuid>f08cf9a9-1719-41b8-93ea-90e3d4283f99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='64971db3a4e8ae9819877d97']/div[4]/button</value>
      <webElementGuid>d6160f1c-8365-4df9-a2b2-ab242c3f7551</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Detail Transaksi'])[23]/following::button[1]</value>
      <webElementGuid>91ab01b9-c9ea-4590-9c9b-16bf30f22665</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Twitter'])[1]/preceding::button[1]</value>
      <webElementGuid>d8c62ded-ec16-47e5-a1e4-ee2306b1e1e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YouTube'])[1]/preceding::button[1]</value>
      <webElementGuid>028b66cf-acdc-4c1f-a38e-c663f94b5aba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[23]/div[4]/button</value>
      <webElementGuid>c8480676-da6a-43f7-8a01-4579aab5a4ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'cancel-order-button-1' and (text() = 'Batalkan' or . = 'Batalkan')]</value>
      <webElementGuid>3e3e341d-6edf-4ddf-8039-46a7e1a082fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
