<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Batalkan (alert dialog cancel)</name>
   <tag></tag>
   <elementGuidId>0ce3505d-743d-4fb4-80dc-da45abe7a6c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='cancel-order-confirmation-button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cancel-order-confirmation-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4cb45222-c51e-42f8-8351-9477c2c395ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2963393a-02e6-415e-a297-778a1601d6f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-button css-12is16t</value>
      <webElementGuid>bbc5c482-9342-43ab-9c4c-dfa47707d043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cancel-order-confirmation-button</value>
      <webElementGuid>c41c7de3-8015-4106-aad5-e81320199893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Batalkan</value>
      <webElementGuid>084594ac-cde0-410c-aa30-dee7b50f8c3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cancel-order-confirmation-button&quot;)</value>
      <webElementGuid>b276adf4-5e9e-4ecf-94ad-79859b85f18b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='cancel-order-confirmation-button']</value>
      <webElementGuid>8bc8f9ee-2798-4cf0-b3a0-8056d90ef920</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='chakra-modal-cancel-order-alert-dialog']/footer/button[2]</value>
      <webElementGuid>c6fa68a7-55ca-460c-9dfa-34358322e935</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kembali'])[1]/following::button[1]</value>
      <webElementGuid>5e39cc92-3e95-4095-8244-dbd091ccc557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apakah anda yakin ingin membatalkan transaksi?'])[1]/following::button[2]</value>
      <webElementGuid>a4034f91-8925-4591-aa4d-9b5fa2378e4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>e139aac6-2380-4cb5-a009-6af514d687fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'cancel-order-confirmation-button' and (text() = 'Batalkan' or . = 'Batalkan')]</value>
      <webElementGuid>e6e39689-4801-4b4f-bdef-9f3b194f594d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
