<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_close button (modal)</name>
   <tag></tag>
   <elementGuidId>0a4f297b-b0a5-4b79-86e2-a32d98ed9f4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='order-modal-header-close-button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#order-modal-header-close-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9dd96c22-f72d-49e2-a374-352c70358574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d59dd0bc-3a8c-4b52-93ea-0dbfe4c6bc54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>39e9e5b1-dc38-4edb-9ec7-3f9ff1742c90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-modal__close-btn css-1ik4h6n</value>
      <webElementGuid>e966bef9-f8c3-48e2-ab62-402e91c3af14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>order-modal-header-close-button</value>
      <webElementGuid>55ef783c-6804-4cbf-aedf-a04f08d2edda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;order-modal-header-close-button&quot;)</value>
      <webElementGuid>7209eb51-3066-40b3-9ce4-c21359c3cd00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='order-modal-header-close-button']</value>
      <webElementGuid>27d28020-4291-4033-8cc5-5eef6ca45f95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='chakra-modal-:rl:']/button</value>
      <webElementGuid>c4b0314b-dac7-4391-a9f7-44040a33f382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'order-modal-header-close-button', '&quot;', ')')])[1]/following::button[1]</value>
      <webElementGuid>ddef3dba-6a50-4b81-b0d7-f35403658a85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Instagram'])[1]/following::button[1]</value>
      <webElementGuid>c2605ea3-36fc-4674-beff-1f5e82a73ec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/button</value>
      <webElementGuid>5c932b4f-c8f4-435e-bf92-80dcec452f19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'order-modal-header-close-button']</value>
      <webElementGuid>14a13857-ece5-45ba-98a5-5849a64e3a6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
