<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Lihat Detail Transaksi</name>
   <tag></tag>
   <elementGuidId>ca65d9f3-2264-4694-a8c0-845bf76bf555</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='detail-order-button-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#detail-order-button-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>33b557be-b3cb-4e05-8b24-37cf0feb168b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>92a8af3e-6e4e-421f-b254-dec485e24b45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-button css-3z7zkq</value>
      <webElementGuid>193f3825-24bd-45c0-aab5-ebc134adf1d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>detail-order-button-1</value>
      <webElementGuid>475b4836-6017-43d1-9ee1-7300a2d09399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lihat Detail Transaksi</value>
      <webElementGuid>1fb8f1c2-18f9-4b2f-b376-5f12da2c6dfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;detail-order-button-1&quot;)</value>
      <webElementGuid>72f090e1-61c5-4c75-a616-8d8263d7dd32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='detail-order-button-1']</value>
      <webElementGuid>9bb78c28-be45-489d-8268-e16fe8ac97c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='64736fbaa29bb2f4bb16e630']/div[4]/div[2]/button</value>
      <webElementGuid>a55b9e8d-d386-4b96-bbb0-9c52aac3e8ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kaos Putih Polos'])[1]/following::button[1]</value>
      <webElementGuid>488ef894-04e9-4c75-9ec8-21d38a52c4b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belanja'])[1]/following::button[1]</value>
      <webElementGuid>de106c37-2857-4e41-b420-784aaa6e40ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batalkan'])[1]/preceding::button[1]</value>
      <webElementGuid>90850ab6-c790-41f0-aeab-4eba398d96ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belanja'])[2]/preceding::button[2]</value>
      <webElementGuid>611328a0-fdba-4800-8215-e574f6c5e449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lihat Detail Transaksi']/parent::*</value>
      <webElementGuid>8218b084-1604-46fe-a6de-5c79691d556e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/button</value>
      <webElementGuid>9b89730d-536c-4721-a0bd-cf48c5a76382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'detail-order-button-1' and (text() = 'Lihat Detail Transaksi' or . = 'Lihat Detail Transaksi')]</value>
      <webElementGuid>58283cf1-7b62-488b-af45-ff55dcf36c2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
