<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Info Penerima section (modal)</name>
   <tag></tag>
   <elementGuidId>c61ef7fe-2681-410b-9868-b2485ac19232</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='chakra-modal--body-order-modal']/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fff77c67-8336-4f8a-a7f6-bb80203a7474</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1bw0yvr</value>
      <webElementGuid>d16f92d2-ce80-48ff-a8ef-5a53f2d4c399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Info PenerimaNama :Usery TaddNo HP:08134489884Alamat:Kp. Sejahtera Nusa Bangsa Satu Indonesia No. 23 Rt.03/Rw.09, Padalarang Tengah, Bandung Barat, Jawa Barat, </value>
      <webElementGuid>4f5d0750-24c2-4a5e-b64f-d9e246ba615a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chakra-modal--body-order-modal&quot;)/div[@class=&quot;css-1bw0yvr&quot;]</value>
      <webElementGuid>55acee8e-ab77-4018-a400-181eee716171</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chakra-modal--body-order-modal']/div[3]</value>
      <webElementGuid>e48344ce-ad60-4408-b797-54d8e25cf6b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YukJahit'])[2]/following::div[4]</value>
      <webElementGuid>7a0e52a3-fcbe-478e-9511-fc700ffe5eb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div[3]</value>
      <webElementGuid>ec1a5721-58e1-4cb9-898d-99530f880571</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Info Penerima' or . = 'Info Penerima ')]</value>
      <webElementGuid>e6b70fe7-9f5d-4f2d-9e4c-036c344501e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
