<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Apakah anda yakin ingin membatalkan transaksi</name>
   <tag></tag>
   <elementGuidId>359ceab1-2f54-42ec-9da0-31cf103291cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='chakra-modal--body-cancel-order-alert-dialog']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#chakra-modal--body-cancel-order-alert-dialog</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7a2a9fa8-6bea-4989-b663-27cde8e4ecdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-modal__body css-qlig70</value>
      <webElementGuid>148326b4-c6ea-4962-a6b4-00a2a0f87c4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chakra-modal--body-cancel-order-alert-dialog</value>
      <webElementGuid>674cec5a-0da9-489c-ba3d-237b29c45c1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apakah anda yakin ingin membatalkan transaksi?</value>
      <webElementGuid>851a74f7-7c9b-4f87-8494-f6a2331ba896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chakra-modal--body-cancel-order-alert-dialog&quot;)</value>
      <webElementGuid>3683399e-d805-4722-ac16-1dc031de57a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='chakra-modal--body-cancel-order-alert-dialog']</value>
      <webElementGuid>30e0d7b8-eb03-4da3-8a2b-9d56ba3d6021</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='chakra-modal-cancel-order-alert-dialog']/div</value>
      <webElementGuid>07ec16e6-9236-4d49-b222-95a2787556e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'chakra-modal--body-cancel-order-alert-dialog', '&quot;', ')')])[1]/following::div[6]</value>
      <webElementGuid>7b17be61-a287-4e5f-8d58-910d5d404346</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Instagram'])[1]/following::div[9]</value>
      <webElementGuid>8bfc2cf4-daf4-4847-98af-c437079ee480</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kembali'])[1]/preceding::div[1]</value>
      <webElementGuid>2fa1659c-4ac4-45fe-a01f-93b1a013e245</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batalkan'])[55]/preceding::div[1]</value>
      <webElementGuid>eaf2fce4-60ad-41cf-8428-510dfcdd1b6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Apakah anda yakin ingin membatalkan transaksi?']/parent::*</value>
      <webElementGuid>8f439d61-4f07-4baf-ab92-1556fb3f00fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div</value>
      <webElementGuid>493c6014-7cd6-4e32-97c9-25ef467ed071</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'chakra-modal--body-cancel-order-alert-dialog' and (text() = 'Apakah anda yakin ingin membatalkan transaksi?' or . = 'Apakah anda yakin ingin membatalkan transaksi?')]</value>
      <webElementGuid>1256db61-58d4-4f6a-b3fd-d20b47460001</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
