<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_order Card (index pertama)</name>
   <tag></tag>
   <elementGuidId>7ea3a394-303b-4abe-b728-91ed03d9b72f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#64736fbaa29bb2f4bb16e630</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='order-card-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9ebaa25b-ff59-4b32-aa07-7d73af187a76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-card chakra-container css-v7jly3</value>
      <webElementGuid>32325cee-a7c3-4e76-a6db-711b5e5f6e12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>64736fbaa29bb2f4bb16e630</value>
      <webElementGuid>0284475f-bce6-46f9-9aec-e5ae731af7d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BelanjaSelesai28 Mei 2023 | 22:14 WIB64736fbaa29bb2f4bb16e630Kaos Putih PolosTotal BelanjaRp 140.000Lihat Detail TransaksiBatalkan</value>
      <webElementGuid>b336ff81-ee4d-4e1b-90eb-99db2048d98e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;64736fbaa29bb2f4bb16e630&quot;)</value>
      <webElementGuid>0b63ed8b-d529-46bb-b27c-1a06c6724b8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='order-card-1']</value>
      <webElementGuid>2f79ddc4-103e-407b-9472-2f3269127606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div</value>
      <webElementGuid>8e99bdba-7ad3-499d-9953-fb652a1c514e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Transaksi'])[1]/following::div[1]</value>
      <webElementGuid>5d9d0179-6ba4-431e-a237-e8c3e2428162</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keluar'])[1]/following::div[2]</value>
      <webElementGuid>35daaf76-4766-4439-b32f-f18fcd728ef1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div</value>
      <webElementGuid>32778645-c352-49d7-a937-1dd2664e274e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'order-card-1')]</value>
      <webElementGuid>cd776ff5-0fe0-471b-a6ab-80d46d0c9969</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
