<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_BelanjaSelesai25 Juni 2023  2309 WIB649_286765</name>
   <tag></tag>
   <elementGuidId>f0e21f0a-88e1-4717-a0fa-b144f22de0d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='order-card-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#order-card-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f711bd51-1c51-4bb1-bf32-a8e32a0725a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-card chakra-container css-v7jly3</value>
      <webElementGuid>b4d1cdc5-373d-4ca2-85aa-8b2d57d3aa85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>order-card-1</value>
      <webElementGuid>39cc83d0-7abf-41a5-8811-7bdfb1856c61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BelanjaSelesai25 Juni 2023 | 23:09 WIB649866c26887d0ab718ef2e8Kaos Hitam Polos dan 1 produk lainnyaTotal BelanjaRp 5.500.000Lihat Detail TransaksiBatalkan</value>
      <webElementGuid>9bcb6ddf-7750-404b-b7aa-1c61d1440c1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;order-card-1&quot;)</value>
      <webElementGuid>958b9934-cb56-4a54-8e32-fc8fb57596cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='order-card-1']</value>
      <webElementGuid>dbaf8403-9da0-4ec3-8159-f3338b2e5750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div</value>
      <webElementGuid>3cb1a784-11f4-4a21-bc08-17c9eab06a19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Transaksi'])[1]/following::div[1]</value>
      <webElementGuid>0b27b283-275c-4388-a01c-00aaa24c35a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keluar'])[1]/following::div[2]</value>
      <webElementGuid>9c274701-85cb-4abc-b07a-041e15e0e44c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div</value>
      <webElementGuid>d837ef6c-4724-4d68-9bd7-5374cc23f95d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'order-card-1' and (text() = 'BelanjaSelesai25 Juni 2023 | 23:09 WIB649866c26887d0ab718ef2e8Kaos Hitam Polos dan 1 produk lainnyaTotal BelanjaRp 5.500.000Lihat Detail TransaksiBatalkan' or . = 'BelanjaSelesai25 Juni 2023 | 23:09 WIB649866c26887d0ab718ef2e8Kaos Hitam Polos dan 1 produk lainnyaTotal BelanjaRp 5.500.000Lihat Detail TransaksiBatalkan')]</value>
      <webElementGuid>26669f04-0635-4b79-b23c-2a59da86869b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
