<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_order status</name>
   <tag></tag>
   <elementGuidId>b49762bf-ac1b-44ae-8aba-9c6eb61ae47c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#order-status</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='order-status']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>c013cef6-1132-4b1d-9cc7-bb8cd780d529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-text css-1alepa3</value>
      <webElementGuid>43966cb9-ae10-43fd-93f8-be4a39e18f08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>order-status</value>
      <webElementGuid>a40d5b7a-516b-4e8d-9337-598f87247153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selesai</value>
      <webElementGuid>52480794-0383-497c-b470-26760ca9ba32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;64736fbaa29bb2f4bb16e630&quot;)/div[@class=&quot;css-1hu54g4&quot;]/p[@id=&quot;order-status&quot;]</value>
      <webElementGuid>8b0c0c38-ca5c-45e7-9e1c-c708c2005bff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='order-status']</value>
      <webElementGuid>02369411-665b-4d54-b913-6e962ad7b6c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[]/div/p</value>
      <webElementGuid>52b1ec32-8bb7-4328-95ba-418be398b5a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belanja'])[1]/following::p[1]</value>
      <webElementGuid>a280a801-75dd-44da-bed5-77a70c10932f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Transaksi'])[1]/following::p[1]</value>
      <webElementGuid>20ba89e8-90f5-41cc-b571-9fdc5a027a01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kaos Putih Polos'])[1]/preceding::p[3]</value>
      <webElementGuid>69fae0b6-5025-4f1a-a8b7-64659d23d34a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Detail Transaksi'])[1]/preceding::p[5]</value>
      <webElementGuid>73023988-b806-42c8-b51e-4467f2f6fbda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Selesai']/parent::*</value>
      <webElementGuid>cac37397-1f1e-42dc-a507-da80aae57721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>52c04152-ec8f-43d3-ac25-c2ebe6c6ab6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'order-status']</value>
      <webElementGuid>8139696e-ce99-4ff3-bc33-559e06d52a27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
