<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>section_Modal</name>
   <tag></tag>
   <elementGuidId>030553a6-388a-4259-ab15-353883f31197</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='chakra-modal-order-modal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>section</value>
      <webElementGuid>10db58a1-ec57-4b00-80b4-330f04d602a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-modal__content css-izwmzu</value>
      <webElementGuid>5499df53-c18f-4489-a28e-7ef9cbc85d2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>d4205eda-3760-44b4-9a7c-82bbba4b9d2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chakra-modal-:rl:</value>
      <webElementGuid>0490ebb1-6e03-4797-a177-3c6939649de0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>795c493e-2957-4d45-8be8-b116dfd2fb6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>34de14a6-5964-4979-a765-9a887926494c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-projection-id</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>4922cbef-ca2c-41a6-8c8e-a2346fa1d748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>chakra-modal--header-:rl:</value>
      <webElementGuid>c9c567de-7f94-4527-9fac-7a938d08d0ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>chakra-modal--body-:rl:</value>
      <webElementGuid>26295854-9bfb-4528-8404-3f65dc1d565d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Detail TransaksiSelesaiID Transaksi64736fbaa29bb2f4bb16e630Tanggal 28 Mei 2023 | 22:14 WIBDetail ProdukKaos Putih Polos x1by YukJahitTotal HargaRp 140.000Catatan :sadInfo PenerimaNama :Usery TaddNo HP:08134489884Alamat:Kp. Sejahtera Nusa Bangsa Satu Indonesia No. 23 Rt.03/Rw.09, Padalarang Tengah, Bandung Barat, Jawa Barat, Rincian PembayaranMetode Pembayaran gopayTotal Harga Rp 140.000</value>
      <webElementGuid>6ca91924-4ae8-42a4-954b-89dc6d727827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chakra-modal-:rl:&quot;)</value>
      <webElementGuid>7772202b-6491-4a59-8b90-0dc8ae4612be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//section[@id='chakra-modal-order-modal']</value>
      <webElementGuid>dfd4dc81-a359-4a48-89c0-af0cc5c21681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'chakra-modal-:rl:', '&quot;', ')')])[1]/following::section[1]</value>
      <webElementGuid>570980ee-6ab7-4566-b98f-4eaeac03e639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Instagram'])[1]/following::section[1]</value>
      <webElementGuid>a763e4cf-f87b-41cb-979a-74a8133304c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section</value>
      <webElementGuid>32e4c7e8-1719-4bbb-836a-bef824b653ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//section[@id = 'chakra-modal-order-modal']</value>
      <webElementGuid>ece1dac0-8592-4f86-ac7e-c57e85f36703</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
