<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>section_Detail TransaksiSelesaiID Transaksi_b2a399</name>
   <tag></tag>
   <elementGuidId>a818d22d-4a93-4733-9057-5669e744bf7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='chakra-modal-order-modal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#chakra-modal-order-modal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>section</value>
      <webElementGuid>5d68e1af-cbb8-452a-b5ef-05a6b25a5a2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-modal__content css-izwmzu</value>
      <webElementGuid>8d067c8b-f2e4-4dcf-a63f-d9d7dcd494cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>09f582b0-8cc9-442d-bc77-3aa6b0e49967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chakra-modal-order-modal</value>
      <webElementGuid>ca1a5dc8-4b57-4f28-bf31-7d1145f0bd63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>d0cdd1f8-1f56-4ff0-896d-ca48ebbefa3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0dcce627-a18a-41c9-952b-2e1d5b643362</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-projection-id</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>be4503f5-0726-47cd-87f5-5b7508b5b4ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>chakra-modal--header-order-modal</value>
      <webElementGuid>f2882884-4041-4ef4-a47c-5bb67780ee95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>chakra-modal--body-order-modal</value>
      <webElementGuid>5573b7ab-c06a-4db5-8eeb-35568a8ccecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Detail TransaksiSelesaiID Transaksi649866c26887d0ab718ef2e8Tanggal 25 Juni 2023 | 23:09 WIBDetail ProdukKaos Hitam Polos x1by YukJahitTotal HargaRp 125.000Kemeja Panjang Biru Gelap x25by YukJahitTotal HargaRp 5.375.000Catatan :Semuanya Ukuran XXLInfo PenerimaNama :system test (1)No HP:08123456789Alamat:System test addressRincian PembayaranMetode Pembayaran gopayTotal Harga Rp 5.500.000</value>
      <webElementGuid>589840fa-7fe2-4a68-b612-3b27b44cea90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chakra-modal-order-modal&quot;)</value>
      <webElementGuid>94856461-7e5a-42b0-a813-742396357f2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//section[@id='chakra-modal-order-modal']</value>
      <webElementGuid>55a9b2ca-28fd-48da-b4b8-b242f9d97daa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'chakra-modal-order-modal', '&quot;', ')')])[1]/following::section[1]</value>
      <webElementGuid>562d0839-6e0b-4b13-8433-10e6a8752575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Instagram'])[1]/following::section[1]</value>
      <webElementGuid>f1d1cc0b-e3bb-4d73-a467-422c029eb309</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section</value>
      <webElementGuid>1ec3ba38-f4df-4b6c-8b33-858797e18271</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//section[@id = 'chakra-modal-order-modal' and (text() = 'Detail TransaksiSelesaiID Transaksi649866c26887d0ab718ef2e8Tanggal 25 Juni 2023 | 23:09 WIBDetail ProdukKaos Hitam Polos x1by YukJahitTotal HargaRp 125.000Kemeja Panjang Biru Gelap x25by YukJahitTotal HargaRp 5.375.000Catatan :Semuanya Ukuran XXLInfo PenerimaNama :system test (1)No HP:08123456789Alamat:System test addressRincian PembayaranMetode Pembayaran gopayTotal Harga Rp 5.500.000' or . = 'Detail TransaksiSelesaiID Transaksi649866c26887d0ab718ef2e8Tanggal 25 Juni 2023 | 23:09 WIBDetail ProdukKaos Hitam Polos x1by YukJahitTotal HargaRp 125.000Kemeja Panjang Biru Gelap x25by YukJahitTotal HargaRp 5.375.000Catatan :Semuanya Ukuran XXLInfo PenerimaNama :system test (1)No HP:08123456789Alamat:System test addressRincian PembayaranMetode Pembayaran gopayTotal Harga Rp 5.500.000')]</value>
      <webElementGuid>594a461f-5305-4917-bb54-840d42335f14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
