<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Rp 215.000</name>
   <tag></tag>
   <elementGuidId>7ef90f01-ee25-4750-91fc-7a94978d11dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='product-price']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#product-price</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>c70b2416-a07f-42af-96a5-df76458b7f8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-text css-14rniuf</value>
      <webElementGuid>52d73245-cf2f-4706-a5af-74fa70db3ebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product-price</value>
      <webElementGuid>6a5b0c70-6602-4853-a1d4-4ddcac806759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rp 215.000</value>
      <webElementGuid>59ee247a-f830-4347-8ad7-9e4f1b592a11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-price&quot;)</value>
      <webElementGuid>854795cc-2b31-423c-a964-a2594792feb7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='product-price']</value>
      <webElementGuid>3ad575ce-7ba5-44ed-b0ac-446ef4a2cb36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/form/div/p[2]</value>
      <webElementGuid>01472601-2308-4f86-9d4b-42d8d83398cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kemeja Panjang Biru Gelap'])[2]/following::p[2]</value>
      <webElementGuid>174377f9-f854-4b84-b074-6c27dab0b3cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kemeja Panjang Biru Gelap'])[1]/following::p[2]</value>
      <webElementGuid>ed604651-a4b1-464c-8e61-55b2f105bded</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/preceding::p[2]</value>
      <webElementGuid>2f712727-6dbb-4e5d-a156-1c057dbab8f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/preceding::p[2]</value>
      <webElementGuid>ed7f308e-4bf1-4665-9a83-9a03ff091537</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Rp']/parent::*</value>
      <webElementGuid>2b3beae2-742a-44d8-b312-3d5e9ca43b52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]</value>
      <webElementGuid>d3129942-57f1-41ff-a952-285309f8bada</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'product-price' and (text() = 'Rp 215.000' or . = 'Rp 215.000')]</value>
      <webElementGuid>a1b52c4d-d29f-4740-8956-c9f069dd6d3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
