<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_YukJahitMasukDaftarYukJahitDaftarNamaAl_ba8547</name>
   <tag></tag>
   <elementGuidId>5c41339e-9068-4395-b689-cfa13a55a5b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#root</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>316279b4-0427-4f8f-b96f-4b5c0b45358f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>010a95a8-1f20-4e62-8580-a45e2dcf946a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>YukJahitMasukDaftarYukJahitDaftarNama*Alamat Email*We will never share your email.Password*Konfirmasi Password*Nomor HP*Alamat Lengkap*Alamat LengkapDaftar© 2023 YukJahit. All rights reservedTwitterYouTubeInstagram</value>
      <webElementGuid>71be6b5d-a06f-4ca8-b421-45c66c481df4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)</value>
      <webElementGuid>1d9228f4-e8ac-452b-b53d-1ba72b6cff6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='root']</value>
      <webElementGuid>18d2f1a3-a94f-43de-b5a0-c2113e2046a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div</value>
      <webElementGuid>15fbbb2f-fe4d-4dd4-83d0-02c4afbecdf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'root' and (text() = 'YukJahitMasukDaftarYukJahitDaftarNama*Alamat Email*We will never share your email.Password*Konfirmasi Password*Nomor HP*Alamat Lengkap*Alamat LengkapDaftar© 2023 YukJahit. All rights reservedTwitterYouTubeInstagram' or . = 'YukJahitMasukDaftarYukJahitDaftarNama*Alamat Email*We will never share your email.Password*Konfirmasi Password*Nomor HP*Alamat Lengkap*Alamat LengkapDaftar© 2023 YukJahit. All rights reservedTwitterYouTubeInstagram')]</value>
      <webElementGuid>8a3b0570-d8f4-43e5-8031-07d1998adcdc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
