<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Daftar</name>
   <tag></tag>
   <elementGuidId>ac7f8b08-ff52-438b-b306-55d4272dce4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2.chakra-text.css-1fqhvzd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>b23bb5fa-dfdd-47ec-b119-caa83f4c4f09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-text css-1fqhvzd</value>
      <webElementGuid>ed9a0e21-d25e-4590-997e-5b1f915b7b37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daftar</value>
      <webElementGuid>d0829526-fab8-4d14-b94b-49f4bada423d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;chakra-container css-7wi6f6&quot;]/div[@class=&quot;css-gmuwbf&quot;]/h2[@class=&quot;chakra-text css-1fqhvzd&quot;]</value>
      <webElementGuid>b822fc5b-533f-4819-833d-7c873549d32f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/h2</value>
      <webElementGuid>99870670-11b9-4d1e-b962-2cd601c17a34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jahit'])[2]/following::h2[1]</value>
      <webElementGuid>fdbb145e-84a9-4e83-9557-d50d068def7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>2be4919a-8c04-49e9-8b08-af752498b1ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Daftar' or . = 'Daftar')]</value>
      <webElementGuid>8b28340c-969e-46c1-b43e-ab0cff9c4467</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
