<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nomor HP_phone</name>
   <tag></tag>
   <elementGuidId>a32fdc55-0657-4d62-9dfb-5519e71a00ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#register-phone-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='register-phone-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cbb5a49f-ef57-4abd-98b5-7fd2ce2ca5df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>8455e6f4-4065-47de-8de4-27bbc7cfc89c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phone</value>
      <webElementGuid>954062ad-cf23-44c5-bdf7-32900ff61905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>register-phone-input</value>
      <webElementGuid>a97ae7dd-eaab-4402-bd08-4a21cde5bebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3a305ac2-0268-410c-95b5-c5e97a3ea62e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-input css-1kp110w</value>
      <webElementGuid>f0da4686-1fde-4759-8e2f-43fb3dcb3172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;register-phone-input&quot;)</value>
      <webElementGuid>7090eedc-7bbb-45b5-9b5a-49bdfcb2f099</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='register-phone-input']</value>
      <webElementGuid>59c62699-6cec-44a3-972f-76d75865f8ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/form/div[5]/input</value>
      <webElementGuid>d0093f0a-fe45-420c-a466-7146c9f30b0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>b3034e6f-27fa-4e4d-802b-61cb6d32462d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'phone' and @id = 'register-phone-input']</value>
      <webElementGuid>47c35d2e-20dc-43b4-986a-89c777173a3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
