<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Alamat Lengkap</name>
   <tag></tag>
   <elementGuidId>8d7cae0e-083e-4980-a8a7-c0e02190fb1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[contains(text(), 'Alamat Lengkap')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>4b89e889-5be0-4451-808d-8553cfd94e91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-:rb:-label</value>
      <webElementGuid>7cbe9447-5a15-4137-9728-4bc036bb88dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>field-:rb:</value>
      <webElementGuid>fbd1bafc-1fe4-4b5a-b4f7-5818db38ac98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-form__label css-g6pte</value>
      <webElementGuid>6bcbc147-94d8-4e71-833d-2be5abdb71db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Alamat Lengkap*</value>
      <webElementGuid>20c29d83-f1ed-431a-af2a-395ff83aff05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-:rb:-label&quot;)</value>
      <webElementGuid>04394646-81a3-4606-b5a6-033c3e616d7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[contains(text(), 'Alamat Lengkap')]</value>
      <webElementGuid>5d0f7175-5c22-4c63-9b95-766483b302ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/form/div[6]/label</value>
      <webElementGuid>f3d8f638-0ef2-459d-92db-021b23076448</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat Lengkap'])[1]/preceding::label[1]</value>
      <webElementGuid>11806d99-6b68-4148-9300-c53fecf487cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar'])[3]/preceding::label[1]</value>
      <webElementGuid>30a77f4d-bab8-422f-9ca4-6841e70bbd8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Alamat Lengkap']/parent::*</value>
      <webElementGuid>d1a7a33e-2dd4-4eec-9de7-c4f4b16b1794</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/label</value>
      <webElementGuid>12ad595a-1ffc-4c8b-96af-74c23a5ed1a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'field-:rb:-label' and (text() = 'Alamat Lengkap*' or . = 'Alamat Lengkap*')]</value>
      <webElementGuid>1851b877-a0b0-4e4f-8cfb-bd3c45b80143</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
