<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Alamat Email</name>
   <tag></tag>
   <elementGuidId>c88764cd-2e32-49d0-8099-96be64ad89e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[contains(text(), 'Email')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>df6ab440-fbaa-4706-8681-ec588c85cbe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-:r3:-label</value>
      <webElementGuid>7256e73c-b326-4e27-ae76-49448d09bd0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>field-:r3:</value>
      <webElementGuid>2db2a273-2d8e-496e-99d6-23ec7119bb62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-form__label css-g6pte</value>
      <webElementGuid>6f446a63-6161-4b88-bdc9-4191e168af35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Alamat Email*</value>
      <webElementGuid>1abfa91c-aba5-47ab-ae03-8420f85b9ef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-:r3:-label&quot;)</value>
      <webElementGuid>c69c12b1-a997-4b2b-95f8-9b2791d9b092</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[contains(text(), 'Email')]</value>
      <webElementGuid>81f1df1b-0aa4-4b76-ac44-ec699adc3daa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/form/div[2]/label</value>
      <webElementGuid>c225e6eb-3b5f-4307-8bd2-62bbc903ba64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar'])[2]/following::label[2]</value>
      <webElementGuid>91c8909c-809e-46e0-aa1a-121062052ba3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='We will never share your email.'])[1]/preceding::label[1]</value>
      <webElementGuid>00514453-ac33-47ba-995d-80778497ba55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Alamat Email']/parent::*</value>
      <webElementGuid>97ec5bb9-701c-4c48-9c9c-d3b30fa8c563</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label</value>
      <webElementGuid>8aafbefb-34b8-4b02-a7e9-3d903f8d2fb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'field-:r3:-label' and (text() = 'Alamat Email*' or . = 'Alamat Email*')]</value>
      <webElementGuid>9eaac6b0-6f68-4720-a553-b06bd31098bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
