<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Kaos Putih Polosby YukJahitRp 140.000</name>
   <tag></tag>
   <elementGuidId>bc71f6f1-254e-4e57-8d7d-abb50d377f0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='product-card-2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#product-card-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5a29bb9b-ce6f-41b9-834c-aa22ec74e023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product-card-2</value>
      <webElementGuid>a52031c0-1874-4a40-aa02-1a09b3b86a5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-linkbox css-13i0ih4</value>
      <webElementGuid>2fbaefa1-1ffc-41aa-9864-c1082962e70d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/products/6470bf8a924d47fc9f34a0a6</value>
      <webElementGuid>3cdbe51e-fdd9-485b-beee-020be6c14a4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kaos Putih Polosby YukJahitRp 140.000</value>
      <webElementGuid>b75ee552-c171-4b84-81a6-b52f6c556de1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-card-2&quot;)</value>
      <webElementGuid>2d065ccf-235b-4c7f-bf03-215d081b0062</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='product-card-2']</value>
      <webElementGuid>cd8fc37a-b535-4f90-9ace-d49962131620</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/a[2]</value>
      <webElementGuid>7cd9dee1-8b34-4b06-922a-768f069dfd1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YukJahit'])[2]/following::a[1]</value>
      <webElementGuid>85c20665-b1e3-4d30-b3ec-718e3a05e918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pencarian'])[1]/following::a[2]</value>
      <webElementGuid>6536878d-f8fa-429f-8033-af1ee99e4cb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YukJahit'])[4]/preceding::a[1]</value>
      <webElementGuid>cb81088d-8bc9-413f-9409-a81a066295fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/products/6470bf8a924d47fc9f34a0a6')]</value>
      <webElementGuid>22401944-257b-45df-a4c3-b30800f1c2b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a[2]</value>
      <webElementGuid>f76674c3-e355-467f-8f07-161a65cf0949</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'product-card-2' and @href = '/products/6470bf8a924d47fc9f34a0a6' and (text() = 'Kaos Putih Polosby YukJahitRp 140.000' or . = 'Kaos Putih Polosby YukJahitRp 140.000')]</value>
      <webElementGuid>9443e705-a48e-4d3b-b980-63cbfd5b1343</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
