<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Jahit_nav-search-input</name>
   <tag></tag>
   <elementGuidId>abf76056-ce79-4f6c-bde5-a33e452b3fa7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nav-search-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nav-search-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>759ae6c7-2948-447f-a476-b1a989faf3ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cari sesuatu disini...</value>
      <webElementGuid>f7ff8c35-0508-41de-a95d-270b7ac31eb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-search-input</value>
      <webElementGuid>dbce7560-2001-401c-9dc1-b4f13eba9cad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-input css-1xxrzf0</value>
      <webElementGuid>5fa6c887-5992-44d7-8291-2ff3cbb1b328</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>kaos</value>
      <webElementGuid>e573385a-98dc-46dc-8665-f4df3e0614bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-search-input&quot;)</value>
      <webElementGuid>abe868be-bc21-4772-bd8e-943331da916d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nav-search-input']</value>
      <webElementGuid>bae3dcdd-b683-4cbc-8f8d-90a16d884c86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/form/div/input</value>
      <webElementGuid>e15c82ea-824c-4214-baec-d5938e536dd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>4ebeefe5-33b0-4edd-9804-a799adfa0d1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Cari sesuatu disini...' and @id = 'nav-search-input']</value>
      <webElementGuid>d788ddb1-9113-407a-b51d-534421aac396</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
