<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nomor HP_phone</name>
   <tag></tag>
   <elementGuidId>b25b1379-ca2e-48df-bf63-02fbc97def5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='edit-profile-modal-phone-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#edit-profile-modal-phone-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2e30e63f-1cca-4300-a75b-4b34e5e2f1a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>3cab4140-8691-4bdd-a82c-b83489d066fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phone</value>
      <webElementGuid>c51feb87-cbd5-40b0-bb7a-90d1d58b96f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-profile-modal-phone-input</value>
      <webElementGuid>1e25095e-39b5-45b2-bff3-c3f19d57dc1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-input css-1kp110w</value>
      <webElementGuid>b64d1bb7-a107-4905-b92d-110f6d5c621f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>08123456789</value>
      <webElementGuid>4c43f6e5-c68c-4c83-9a49-1f5290c78927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-profile-modal-phone-input&quot;)</value>
      <webElementGuid>708600c5-3968-4621-a3cd-3b04fef28502</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='edit-profile-modal-phone-input']</value>
      <webElementGuid>b72aed70-4f38-4ba7-b83a-3701df2680cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chakra-modal--body-:r29:']/div/div[2]/input</value>
      <webElementGuid>fbf9fcad-9ba6-4ef4-896e-a6ad3e1670ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>6bbbd06a-63f9-4261-a9e6-af5974992c8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'phone' and @id = 'edit-profile-modal-phone-input']</value>
      <webElementGuid>de89c05d-5e84-4f60-a5e5-852e850cbc76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
