<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Jahit_nav-search-input</name>
   <tag></tag>
   <elementGuidId>3cf41081-50f5-487e-a8cc-ad65da86f9a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nav-search-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nav-search-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8ca3dd78-f4ed-45b7-9543-8983dd1b2e9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cari sesuatu disini...</value>
      <webElementGuid>1b4c0e09-8521-4400-9897-bea1b5de53a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-search-input</value>
      <webElementGuid>ab1dd037-8d3d-4a82-9d75-f8f05de07346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-input css-1xxrzf0</value>
      <webElementGuid>26b823b5-b8e0-428a-bcbd-64d3798c2ced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-search-input&quot;)</value>
      <webElementGuid>d6ff5968-d573-4f48-9711-0189de8e12b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nav-search-input']</value>
      <webElementGuid>7f0360a6-c5b7-4119-a9cd-608a512fae4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/form/div/input</value>
      <webElementGuid>f54cb68c-0912-4ec5-8889-c5fe537ed175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>736dd79f-c3c4-4cf3-97da-20c333c7e8b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Cari sesuatu disini...' and @id = 'nav-search-input']</value>
      <webElementGuid>07df8807-617c-428f-aaa8-7227b837baf2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
