<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Kaos Putih Polosby YukJahitRp 140.000</name>
   <tag></tag>
   <elementGuidId>dfa78a56-6557-481d-9b64-a8374df057f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#product-card-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='product-card-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5241dcf9-2d85-42ec-acd3-8272f7d48139</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product-card-2</value>
      <webElementGuid>5d96e608-5593-4861-b5fc-098590a3c848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-linkbox css-13i0ih4</value>
      <webElementGuid>1e3e14d0-4511-4a48-b2e1-29249118167a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/products/6470bf8a924d47fc9f34a0a6</value>
      <webElementGuid>77d1de25-b6b2-4df4-8a30-eab3a98377f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kaos Putih Polosby YukJahitRp 140.000</value>
      <webElementGuid>09ee3e2b-0d9e-4b73-976d-ef33a792a646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-card-2&quot;)</value>
      <webElementGuid>c1038315-0aa2-45d0-883a-74752a4a2ab1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='product-card-2']</value>
      <webElementGuid>988a03e4-cec6-4ef3-857f-514488dfdf43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/a[2]</value>
      <webElementGuid>bc7e53b8-fb6d-4997-8b60-06617ac04083</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YukJahit'])[2]/following::a[1]</value>
      <webElementGuid>86261ba7-c890-42dd-ab49-94ad8da6d491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Produk Terbaru'])[1]/following::a[2]</value>
      <webElementGuid>fe03a373-aeec-41bc-9230-98f724d6fc96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YukJahit'])[4]/preceding::a[1]</value>
      <webElementGuid>52e4c616-dcca-4031-bb54-7be82fa70ce6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/products/6470bf8a924d47fc9f34a0a6')]</value>
      <webElementGuid>78750552-4eb4-4f22-a21a-b2f144f258d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a[2]</value>
      <webElementGuid>e8365221-3327-4590-ab97-63a94ab4484d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'product-card-2' and @href = '/products/6470bf8a924d47fc9f34a0a6' and (text() = 'Kaos Putih Polosby YukJahitRp 140.000' or . = 'Kaos Putih Polosby YukJahitRp 140.000')]</value>
      <webElementGuid>e1ea56c5-4497-4249-8d30-8323171aca95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
