<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Kaos Abu Polosby YukJahitRp 180.000</name>
   <tag></tag>
   <elementGuidId>9172ea1d-36da-432b-9731-bf69886d43c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='product-card-4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#product-card-4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5fb9059c-df1d-4204-a79a-e329c69c560a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product-card-4</value>
      <webElementGuid>2affd694-3ef4-49f8-a9c9-ba435c09954d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-linkbox css-13i0ih4</value>
      <webElementGuid>08cd4266-bb80-46b1-996a-cc8e83429196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/products/647eccc85d9dc43738ff4b7f</value>
      <webElementGuid>f6cdcd2b-c6c3-4b17-a50b-058380884265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kaos Abu Polosby YukJahitRp 180.000</value>
      <webElementGuid>1427e660-7dd0-4db9-b0c3-fda3a33ea91a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-card-4&quot;)</value>
      <webElementGuid>8b7ba5cf-f0ea-4b00-a3b2-ecfe2fd759f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='product-card-4']</value>
      <webElementGuid>1fe16a9a-33ab-4bc5-a80c-0ac4ecc23c68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/a[4]</value>
      <webElementGuid>aa872fe8-b8c8-40f9-b0cc-7de05a98747c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YukJahit'])[4]/following::a[1]</value>
      <webElementGuid>a7b757a0-748f-4c1e-9916-d2cf97768e62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YukJahit'])[3]/following::a[2]</value>
      <webElementGuid>f6bfb6bd-d29d-4488-9f8b-a6254e9adf71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat semua'])[1]/preceding::a[1]</value>
      <webElementGuid>b1db1c4a-9dca-4c5d-8f83-4aeee785658b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/products/647eccc85d9dc43738ff4b7f')]</value>
      <webElementGuid>80837540-a24c-4e03-b41f-b1827dc185e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]</value>
      <webElementGuid>f9eef79f-f899-4702-a1ac-f077f46b6506</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'product-card-4' and @href = '/products/647eccc85d9dc43738ff4b7f' and (text() = 'Kaos Abu Polosby YukJahitRp 180.000' or . = 'Kaos Abu Polosby YukJahitRp 180.000')]</value>
      <webElementGuid>ae26ec63-aa02-40ea-80e1-363e92be8c1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
