<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Kaos Hitam Polosby YukJahitRp 125.000</name>
   <tag></tag>
   <elementGuidId>0bed018b-02ab-4fa0-bec4-a9b4a1dfff9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='product-card-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#product-card-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>486bb9a9-0c28-43cf-baac-c0dbcce2ca1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product-card-1</value>
      <webElementGuid>4c5e85c2-08be-49ce-989a-fa84c7dcd630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-linkbox css-13i0ih4</value>
      <webElementGuid>8d1dfd48-7613-4c02-877d-7539523a27cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/products/6470bb08484c48978a48c329</value>
      <webElementGuid>e670aace-978b-4c25-9fac-b9918b9177af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kaos Hitam Polosby YukJahitRp 125.000</value>
      <webElementGuid>b0fc0efd-35fa-475e-958b-c7f6042df724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-card-1&quot;)</value>
      <webElementGuid>9bb8790c-0f5b-4cd4-94ce-5ee8b1a6e8bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='product-card-1']</value>
      <webElementGuid>ff91879e-4f27-4f03-b48c-467d0144c055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/a</value>
      <webElementGuid>00883cd6-6d53-4629-9fed-33ad63e12dc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Produk Terbaru'])[1]/following::a[1]</value>
      <webElementGuid>73f47918-0da3-4115-8cb8-682b57ba4fa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar'])[1]/following::a[1]</value>
      <webElementGuid>80ce4466-77f1-4c11-bd3f-57a4606c784d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YukJahit'])[3]/preceding::a[1]</value>
      <webElementGuid>ade00c54-1cdc-4ee2-9b72-752063d349ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/products/6470bb08484c48978a48c329')]</value>
      <webElementGuid>02bfa30e-de7a-48fb-a90f-4fec829be0e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a</value>
      <webElementGuid>e936194a-ddca-48b9-bd71-7f9cda3d6d64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'product-card-1' and @href = '/products/6470bb08484c48978a48c329' and (text() = 'Kaos Hitam Polosby YukJahitRp 125.000' or . = 'Kaos Hitam Polosby YukJahitRp 125.000')]</value>
      <webElementGuid>0326b71e-466a-446b-a33b-267aaa29235c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
