<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Jahit_nav-search-input</name>
   <tag></tag>
   <elementGuidId>e60f115d-1b06-4e6e-96d2-6b666bc3556b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nav-search-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nav-search-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1fca4972-f81f-4dae-b321-7e06cc9e8fb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cari sesuatu disini...</value>
      <webElementGuid>8f04ada6-2461-42ae-be13-61a6e25bc62c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-search-input</value>
      <webElementGuid>6da9b15c-5a96-4426-b496-2074b830fdf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-input css-1xxrzf0</value>
      <webElementGuid>9f29850e-ecae-4b73-aac4-bdb35b8b056d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-search-input&quot;)</value>
      <webElementGuid>3192c9f6-8ba4-4f47-984e-ef7aa8572b2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nav-search-input']</value>
      <webElementGuid>c39f8cb7-472c-4880-96fc-29152f73b6c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/form/div/input</value>
      <webElementGuid>0a2acdb5-7e4d-4e07-bc74-644d1260229f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>d054740d-f9c3-4148-9811-2619d1274a1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Cari sesuatu disini...' and @id = 'nav-search-input']</value>
      <webElementGuid>68b0daf5-22e4-43a1-803e-220a4bb0faab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
