<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Product_name</name>
   <tag></tag>
   <elementGuidId>0950ea85-d17f-4a09-be4a-2f79f94ecc1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='product-name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#product-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>e8e640e1-c214-42a3-83cd-ab3b7eb48293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-text css-157wn8n</value>
      <webElementGuid>136e3c9d-814a-4ec5-8537-b2c832806609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product-name</value>
      <webElementGuid>7f5f769e-ad10-494f-9a13-e7a1089bb274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kaos Abu Polos</value>
      <webElementGuid>c63e515e-9d2f-4ded-9b72-adcca5c7f4dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-name&quot;)</value>
      <webElementGuid>b1e97282-7584-4183-a157-791ba03fc213</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='product-name']</value>
      <webElementGuid>cbd37293-6177-428c-99d8-05a691dd2791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/form/div/h2</value>
      <webElementGuid>80a12307-1ae1-45d7-8b42-da69f0ddf71b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kaos Abu Polos'])[1]/following::h2[1]</value>
      <webElementGuid>db643c76-266a-46d3-8d4c-8f1b458a4f15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Products'])[1]/following::h2[1]</value>
      <webElementGuid>b159fa9f-f2eb-45d5-905e-a7d375793fc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/preceding::h2[1]</value>
      <webElementGuid>89dca265-4cc6-456d-817c-6d49c67ed388</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/preceding::h2[1]</value>
      <webElementGuid>435d3590-fb37-4296-8f68-8e5ad5ed729b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>96aa3e66-720a-4e2d-aec8-4a35f69aee22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'product-name' and (text() = 'Kaos Abu Polos' or . = 'Kaos Abu Polos')]</value>
      <webElementGuid>fa0e7de6-0409-43b1-85f0-269fb4b1c5e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
