<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Product_description</name>
   <tag></tag>
   <elementGuidId>13e368a6-9345-49e3-9f59-50f38c06be37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#product-description</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='product-description']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>8b2b2400-a1cb-4b11-bb64-637e9c9f9768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-text css-xim7xt</value>
      <webElementGuid>f84455d3-4a3e-461c-a202-9bff3ddfb07f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product-description</value>
      <webElementGuid>450ddd30-eaec-458e-95eb-3ff8e6960f6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kaos abu polos yang cocok untuk digunakan oleh laki-laki yang ingin terlihat santai, keren, dan tampan di berbagai tempat khususnya saat tampil di depan umum.</value>
      <webElementGuid>93cc13f5-c91b-41ef-81e1-f2614255b9d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-description&quot;)</value>
      <webElementGuid>ce29f6f3-e1db-4300-b17e-ea9ac518a447</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='product-description']</value>
      <webElementGuid>7a88ed4a-54a3-46d5-a951-83709c848fb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/form/div/p</value>
      <webElementGuid>0d23b692-7c5c-4c55-a1f4-bcdb37924a25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kaos Abu Polos'])[2]/following::p[1]</value>
      <webElementGuid>1f380b81-9c7d-4df0-ba33-8b527b6db19a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kaos Abu Polos'])[1]/following::p[1]</value>
      <webElementGuid>9c086947-9bbd-45d4-8a16-a9c9e2f32edc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/preceding::p[3]</value>
      <webElementGuid>dd6c0f38-54b0-438a-9bbd-47f77aa3b044</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/preceding::p[3]</value>
      <webElementGuid>c9b83969-c257-4d7c-94ac-74845cc0ca37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>3747e0fa-b10e-4777-91fc-984a07a076a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
