<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Rp 180.000</name>
   <tag></tag>
   <elementGuidId>16f9cb11-036e-4c57-87f7-f0e261933018</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.chakra-text.css-14rniuf</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='product-price']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>bf8d7d0e-b493-42e2-bfdf-b6cb1b423591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-text css-14rniuf</value>
      <webElementGuid>d0ce4c64-d867-4213-8a59-2512a6dd57bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rp 180.000</value>
      <webElementGuid>cab5e527-3773-49e3-96d2-d97b991a143b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;chakra-container css-3fg9fx&quot;]/form[@class=&quot;css-bex158&quot;]/div[@class=&quot;css-1005ark&quot;]/p[@class=&quot;chakra-text css-14rniuf&quot;]</value>
      <webElementGuid>789b123e-ac9a-4b59-aa84-14c17572dd4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='product-price']</value>
      <webElementGuid>87212071-222b-4e97-a471-4b641ff8c7f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kaos Abu Polos'])[2]/following::p[2]</value>
      <webElementGuid>6556239d-38d1-4e83-b983-7ecdc846c143</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kaos Abu Polos'])[1]/following::p[2]</value>
      <webElementGuid>4669485c-300e-4bed-a21e-6fbc92401dc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/preceding::p[2]</value>
      <webElementGuid>b0ccd7b1-a5bd-4a01-8f29-14c9b4ce22b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/preceding::p[2]</value>
      <webElementGuid>e99b0420-c388-4588-a0ce-0118e9ae8080</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Rp']/parent::*</value>
      <webElementGuid>63fa737f-8fad-45b9-9910-1745e6a398bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]</value>
      <webElementGuid>958b8faf-2d6a-43dd-8211-817ef7ffafd1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
