<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_KeranjangKaos Hitam Polosby YukJahitRp _1ef66b</name>
   <tag></tag>
   <elementGuidId>1a57d966-38f8-47c4-8953-bccf055f2569</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.chakra-container.css-yah50p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>10ba7408-59c7-436b-aa89-61bd21db4db4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-container css-yah50p</value>
      <webElementGuid>815a4373-1085-4b04-85e3-9b1af185a831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KeranjangKaos Hitam Polosby YukJahitRp 125.000Jumlah: 3Ringkasan belanjaTotal Harga (1 Produk):  Rp 375.000Catatan (Ukuran, Jahitan, etc.): *Ukuran L*wajib diisiTipe Pembayaran: GopayLakukan Pembayaran</value>
      <webElementGuid>c1616a13-dcc2-4095-8417-4879723f2f81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;chakra-container css-yah50p&quot;]</value>
      <webElementGuid>5e79e907-e99f-43a3-aebf-761d9fba1cf7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]</value>
      <webElementGuid>6a490e3a-e399-4d06-83db-0da8f62974d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keluar'])[1]/following::div[1]</value>
      <webElementGuid>a4100e26-2014-4cad-94bc-ccd099ed941b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pembelian'])[1]/following::div[1]</value>
      <webElementGuid>17149bc0-ee23-48a8-881a-d00249b219c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]</value>
      <webElementGuid>d242fa31-f38d-46f0-81b6-2a453c665485</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'KeranjangKaos Hitam Polosby YukJahitRp 125.000Jumlah: 3Ringkasan belanjaTotal Harga (1 Produk):  Rp 375.000Catatan (Ukuran, Jahitan, etc.): *Ukuran L*wajib diisiTipe Pembayaran: GopayLakukan Pembayaran' or . = 'KeranjangKaos Hitam Polosby YukJahitRp 125.000Jumlah: 3Ringkasan belanjaTotal Harga (1 Produk):  Rp 375.000Catatan (Ukuran, Jahitan, etc.): *Ukuran L*wajib diisiTipe Pembayaran: GopayLakukan Pembayaran')]</value>
      <webElementGuid>0968fb40-e832-4041-913e-b0fdf42ef4a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
