<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Alert dialog checkout (in cart)</name>
   <tag></tag>
   <elementGuidId>01c72342-8bba-46ab-ac52-77934b5bdff2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='chakra-modal-checkout-alert-dialog']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>09fd5a6e-b8dc-47ab-a609-19050b7b0234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-modal__body css-qlig70</value>
      <webElementGuid>dd58db1b-ae66-4cc1-8d26-43f6c5885386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chakra-modal--body-:r1j:</value>
      <webElementGuid>7bcef489-e340-4565-9459-4d7f594503a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apakah anda yakin ingin melakukan checkout?</value>
      <webElementGuid>8ff7efd5-dacc-4787-8fa2-056c73bc88f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chakra-modal--body-:r1j:&quot;)</value>
      <webElementGuid>1f25ebdb-61ef-4100-860d-799cf949216d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='chakra-modal-checkout-alert-dialog']</value>
      <webElementGuid>9c9a7167-f020-442e-9a6d-c0478ab7b3fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='chakra-modal-checkout-alert-dialog']/div</value>
      <webElementGuid>608cf64c-29df-44e7-8efa-96fe59d5c593</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'chakra-modal--body-:r1j:', '&quot;', ')')])[1]/following::div[6]</value>
      <webElementGuid>0693627c-d347-4bc3-ab5f-e0ebcd6089fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Instagram'])[1]/following::div[9]</value>
      <webElementGuid>9ce7eade-33cf-4d5f-867d-bd29509f94a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[1]/preceding::div[1]</value>
      <webElementGuid>67bf2895-9985-4076-aa3a-a59efc103540</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkout'])[1]/preceding::div[1]</value>
      <webElementGuid>baa534d6-33c2-4ee3-8cad-faa589e6a92f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Apakah anda yakin ingin melakukan checkout?']/parent::*</value>
      <webElementGuid>f1013ccb-4ea0-4235-9694-cfb40bfd619f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div</value>
      <webElementGuid>ae5b84cd-ffb7-491c-be51-0fa238db0094</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'chakra-modal-checkout-alert-dialog' and (text() = 'Apakah anda yakin ingin melakukan checkout?' or . = 'Apakah anda yakin ingin melakukan checkout?')]</value>
      <webElementGuid>c73836a6-247a-4aee-9e9b-1d9517de048d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
