<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_product in cart (index pertama)</name>
   <tag></tag>
   <elementGuidId>ba38c3e2-087e-4847-9120-42e2f392c9da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cart-product-card-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='cart-product-card-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0c656c33-81b4-4854-929f-cf3662c7155b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-card chakra-container css-15h4j2r</value>
      <webElementGuid>c4c17b0d-6bba-4d9b-a49b-a726db6fd45c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cart-product-card-1</value>
      <webElementGuid>1af38cec-18c7-45ea-9232-ff458e5147ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kaos Hitam Polosby YukJahitRp 125.000Jumlah: 1</value>
      <webElementGuid>e2fb0208-d534-4ec6-9104-794c9ae4f7c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cart-product-card-1&quot;)</value>
      <webElementGuid>8c62a64a-537e-42d3-ae65-ff0b7819c195</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='cart-product-card-1']</value>
      <webElementGuid>f7717120-6e12-42ec-a7ec-30c1d7520531</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='root']/div[2]/div/div</value>
      <webElementGuid>2da95f02-7ef3-4228-8722-04481316413f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keranjang'])[2]/following::div[2]</value>
      <webElementGuid>45d6d18f-31e9-42a2-9527-0472f297adab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keluar'])[1]/following::div[3]</value>
      <webElementGuid>2895ecbb-8463-40c2-9bd3-69a8bef5841d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div</value>
      <webElementGuid>2dcb37ef-5ebc-406e-b3af-41e500e80b86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'cart-product-card-1' and (text() = 'Kaos Hitam Polosby YukJahitRp 125.000Jumlah: 1' or . = 'Kaos Hitam Polosby YukJahitRp 125.000Jumlah: 1')]</value>
      <webElementGuid>39dd1344-ebfc-44a5-b846-17687e82f4f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
