<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Jahit_nav-search-input</name>
   <tag></tag>
   <elementGuidId>e22e083e-0266-4ce8-bf1a-b9b90d2285b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nav-search-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nav-search-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fd88c6bb-4059-40d6-90bf-6011281ee02b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cari sesuatu disini...</value>
      <webElementGuid>4d8260f7-2bb6-4d41-ada8-759d36fc83cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-search-input</value>
      <webElementGuid>dec9b72a-18ce-4c43-92f9-53e84af0d520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-input css-1xxrzf0</value>
      <webElementGuid>ab6ffbac-67e3-42bb-a31e-40dcc5d393c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>kemeja</value>
      <webElementGuid>5e46f83c-1d65-4cda-b8d6-7e877d0bc894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-search-input&quot;)</value>
      <webElementGuid>71504c4b-8c46-43ec-b119-e04df902b83a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nav-search-input']</value>
      <webElementGuid>742db618-ac12-4d95-9364-eeb2684bb327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/form/div/input</value>
      <webElementGuid>f828b8bc-e9b1-4bf7-b3e8-299fa6f27ad2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>fa6b8c5f-b272-4b42-847c-d6adb89d3e20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Cari sesuatu disini...' and @id = 'nav-search-input']</value>
      <webElementGuid>2022b0e9-ff33-45da-a1a4-9068954183d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
