<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Jahit</name>
   <tag></tag>
   <elementGuidId>f67e0d90-65f7-4293-b2c4-b0072dcd11c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='logo-link']/h1/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.chakra-text.css-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>55790eb7-a822-4daa-a70f-e871b1f22892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-text css-0</value>
      <webElementGuid>c8565000-756c-4072-ac1f-057f8b5b9bae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jahit</value>
      <webElementGuid>db120b00-a045-4934-beb7-7235b4c07854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logo-link&quot;)/h1[@class=&quot;chakra-text css-10rv9l1&quot;]/span[@class=&quot;chakra-text css-0&quot;]</value>
      <webElementGuid>24799ec0-ebba-4275-8c31-4f38149499ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='logo-link']/h1/span</value>
      <webElementGuid>5cc5caf8-12a8-4f8e-9d7a-c988a0e3f461</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keranjang'])[1]/preceding::span[1]</value>
      <webElementGuid>3f0b4d80-6505-4b46-b525-d1bb4c5f3029</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Akun'])[1]/preceding::span[2]</value>
      <webElementGuid>82e7d4e4-b924-4bf6-82a4-32c003204b7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Jahit']/parent::*</value>
      <webElementGuid>bdc55d89-098d-4366-bebc-372485a6d699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>c076ec91-78cd-4362-95da-ddb0e1e9a043</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Jahit' or . = 'Jahit')]</value>
      <webElementGuid>804d6acb-90b0-46f1-a8aa-8ef18897db0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
