<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Jahit_nav-search-input</name>
   <tag></tag>
   <elementGuidId>73a3bb32-4ef3-448e-9438-bfec58f8c5d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nav-search-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nav-search-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c3c32d8a-4cb3-43af-8ea5-1eb45df08f4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cari sesuatu disini...</value>
      <webElementGuid>7dc6a57c-d97c-4141-a218-05ac09c3f952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-search-input</value>
      <webElementGuid>078463b3-4b79-48c7-b197-ffb9bf290fe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-input css-1xxrzf0</value>
      <webElementGuid>a4a02c37-1069-4304-b992-9ac2520e2d17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-search-input&quot;)</value>
      <webElementGuid>bffc0f9b-e1ea-4498-a752-12c5492c7965</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nav-search-input']</value>
      <webElementGuid>9f5250f6-700c-4ca0-a189-88caad68cb76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/form/div/input</value>
      <webElementGuid>292597dc-efbb-4da7-a2bb-00f609892d98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>a193ce3d-713f-462a-ab30-dc782d250643</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Cari sesuatu disini...' and @id = 'nav-search-input']</value>
      <webElementGuid>cb324a83-9c1a-4944-8455-2ccd9b9858b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
