<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LinkBox_Semua produk (index pertama)</name>
   <tag></tag>
   <elementGuidId>98ba0952-62ef-4eda-8448-4206000af70f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='product-card-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#product-card-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1917cd60-c81a-4924-9ab5-b0e1bdc59683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product-card-1</value>
      <webElementGuid>3ee7276b-7e07-430d-88b9-95cb8b332837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-linkbox css-13i0ih4</value>
      <webElementGuid>a18d2524-d2e7-48c9-a5e7-e8a65f239c06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/products/6470bb08484c48978a48c329</value>
      <webElementGuid>8d684ab4-cbaf-4fca-a732-5a2ef5f1ef56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kaos Hitam Polosby YukJahitRp 125.000</value>
      <webElementGuid>54c52c73-7c5b-4072-ab4a-dae17ef534ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-card-1&quot;)</value>
      <webElementGuid>3f9101a8-ebbf-44af-b3e0-cbd47db4d377</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='product-card-1']</value>
      <webElementGuid>7d230693-ac16-475c-a2c1-b6d4c8984d70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/a</value>
      <webElementGuid>7bb13af2-e180-4f32-bed1-a850c6021f2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Semua Produk'])[2]/following::a[1]</value>
      <webElementGuid>dd473bf3-8ec0-4a8d-8408-1d5a579d2115</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::a[2]</value>
      <webElementGuid>94a0d9b7-b757-4210-a568-f53016d8d811</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YukJahit'])[3]/preceding::a[1]</value>
      <webElementGuid>5fef1117-14ba-4d6f-820d-f4ca2373069d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/products/6470bb08484c48978a48c329')]</value>
      <webElementGuid>1a2f45fb-33e8-4c00-8f0e-a1df5632b936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>7919d426-3fb7-40b8-bd9b-46777148b2a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'product-card-1' and @href = '/products/6470bb08484c48978a48c329' and (text() = 'Kaos Hitam Polosby YukJahitRp 125.000' or . = 'Kaos Hitam Polosby YukJahitRp 125.000')]</value>
      <webElementGuid>f79bc534-b37f-4aa8-bc27-46458e53ce7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
