<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LinkBox_Semua produk (index terakhir)</name>
   <tag></tag>
   <elementGuidId>f0eb8e6a-07e9-43cc-bc71-b00ad8b03077</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='product-card-5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#product-card-5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>098e4d5e-0196-4500-934d-bc513cbcc2d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product-card-5</value>
      <webElementGuid>ac7d6a68-d836-4154-b141-82403813d3b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-linkbox css-13i0ih4</value>
      <webElementGuid>181de57a-645a-4acd-a376-428c3a141592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/products/647ed0705d9dc43738ff4b9d</value>
      <webElementGuid>3e44826d-22fa-4d42-9012-99a67c551cbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kemeja Panjang Biru Gelapby YukJahitRp 215.000</value>
      <webElementGuid>05c19173-e7cf-4242-b642-70624cbbbb41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-card-5&quot;)</value>
      <webElementGuid>3aa19f1e-195b-4587-9b84-c070232df147</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='product-card-5']</value>
      <webElementGuid>1701ff60-eb42-4352-8a06-285e88a56346</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/a[5]</value>
      <webElementGuid>4fdcb3f9-edeb-4450-80ab-222e042883eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YukJahit'])[5]/following::a[1]</value>
      <webElementGuid>99728225-5d54-4aab-864a-ee7b2e44e0e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YukJahit'])[4]/following::a[2]</value>
      <webElementGuid>6a939ce7-e4a7-494a-90ef-6ba02e486dcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Twitter'])[1]/preceding::a[1]</value>
      <webElementGuid>a072b978-1713-40f1-a084-123b0b2a6c47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/products/647ed0705d9dc43738ff4b9d')]</value>
      <webElementGuid>aa5658df-f0f4-4590-8c32-4ea2b8251cd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[5]</value>
      <webElementGuid>4e55707b-7224-4b63-9678-f0a27022db3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'product-card-5' and @href = '/products/647ed0705d9dc43738ff4b9d' and (text() = 'Kemeja Panjang Biru Gelapby YukJahitRp 215.000' or . = 'Kemeja Panjang Biru Gelapby YukJahitRp 215.000')]</value>
      <webElementGuid>19347db8-d78a-41f6-808b-cb9e33ec2e0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
