<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Nama produk (index pertama)</name>
   <tag></tag>
   <elementGuidId>77b1e0b1-6641-45fe-b728-eeba3a721cc9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.chakra-text.css-2ygcmq</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='product-name-1']/div[2]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>25a12f2e-1785-435d-b073-9f8e6f43f84d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-text css-2ygcmq</value>
      <webElementGuid>feb76919-4395-4cf2-9208-623ac24e9c8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kaos Biru Polos</value>
      <webElementGuid>62004c27-fe9c-4800-8c76-0c93093c67b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-card-1&quot;)/div[@class=&quot;css-2m29wb&quot;]/p[@class=&quot;chakra-text css-2ygcmq&quot;]</value>
      <webElementGuid>58bdb2ef-7978-4f2c-91ae-abaf43795707</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='product-name-1']/div[2]/p</value>
      <webElementGuid>dfdcde4e-6d36-4d87-a4be-3db3da5dcf2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pencarian'])[1]/following::p[1]</value>
      <webElementGuid>4f0ec835-a55f-4a41-9fd4-4672265af2de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::p[1]</value>
      <webElementGuid>b766c802-c6be-4eef-8941-09d24f2948b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YukJahit'])[2]/preceding::p[1]</value>
      <webElementGuid>31e7e208-1365-4110-84d1-98f7b30c9a0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Twitter'])[1]/preceding::p[4]</value>
      <webElementGuid>2d8e9893-33f6-44db-ad7b-57a8ecf45cb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>9d9e2645-e6d4-4217-92e7-e60666093c00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
