<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_link pembayaran</name>
   <tag></tag>
   <elementGuidId>6fa15670-a245-48bb-a098-ec3bfc679ef3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='payment-link']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#payment-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2f65b05b-1926-4f07-b593-aef2956b5125</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>1e5a0ffb-c0fd-43ff-a71c-eadd254d7b56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener</value>
      <webElementGuid>346bd200-0a4c-4807-891c-1bd0f18a402d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-link css-spn4bz</value>
      <webElementGuid>49fb4347-bab1-415c-9c28-c2909d4a69f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payment-link</value>
      <webElementGuid>644ef5ca-8d3c-45c0-b260-13085374acac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://simulator.sandbox.midtrans.com/gopay/partner/app/payment-pin?id=fd095c96-1a63-4627-b540-534d32fdf467</value>
      <webElementGuid>ec6cda52-f514-4d66-a863-346e712c47a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>https://simulator.sandbox.midtrans.com/gopay/partner/app/payment-pin?id=fd095c96-1a63-4627-b540-534d32fdf467</value>
      <webElementGuid>070bb951-e59d-44e9-9774-ebff98b0ea22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-link&quot;)</value>
      <webElementGuid>9740df71-3f72-4ec0-932d-ba3bc3d5bfad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='payment-link']</value>
      <webElementGuid>b4cc54c3-3021-447a-93ec-9ee99655b85e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div[2]/a</value>
      <webElementGuid>12c407d0-9c54-4302-b4d0-a1c83c4d08f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'https://simulator.sandbox.midtrans.com/gopay/partner/app/payment-pin?id=fd095c96-1a63-4627-b540-534d32fdf467')]</value>
      <webElementGuid>388f6dc2-49fe-4a5e-b83c-6051532f8f20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Silahkan akses link berikut'])[1]/following::a[1]</value>
      <webElementGuid>4fcd1e11-2de3-418b-9504-d89237c32a16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[1]/following::a[1]</value>
      <webElementGuid>1706cf4f-6ba8-406b-a68b-fbb04055695e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Twitter'])[1]/preceding::a[1]</value>
      <webElementGuid>65c12927-8abc-4a63-a8b8-712130f82537</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YouTube'])[1]/preceding::a[2]</value>
      <webElementGuid>e26732f8-0945-4982-988c-01884e8199f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='https://simulator.sandbox.midtrans.com/gopay/partner/app/payment-pin?id=fd095c96-1a63-4627-b540-534d32fdf467']/parent::*</value>
      <webElementGuid>de3338d7-84e7-4e25-8816-84b0b68589db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://simulator.sandbox.midtrans.com/gopay/partner/app/payment-pin?id=fd095c96-1a63-4627-b540-534d32fdf467')]</value>
      <webElementGuid>dc0cc540-22ce-404b-b6d5-e4437d33d81d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/a</value>
      <webElementGuid>2ce63282-21ed-4b93-bcac-84c5ee6073c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'payment-link' and @href = 'https://simulator.sandbox.midtrans.com/gopay/partner/app/payment-pin?id=fd095c96-1a63-4627-b540-534d32fdf467' and (text() = 'https://simulator.sandbox.midtrans.com/gopay/partner/app/payment-pin?id=fd095c96-1a63-4627-b540-534d32fdf467' or . = 'https://simulator.sandbox.midtrans.com/gopay/partner/app/payment-pin?id=fd095c96-1a63-4627-b540-534d32fdf467')]</value>
      <webElementGuid>b2191730-2406-4960-bf60-ce607423cc17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
