<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_YukJahitKeranjangAkunProfilPembelianKel_888271</name>
   <tag></tag>
   <elementGuidId>38df0df1-74f5-429f-86ae-9b67727ee9c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#root</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>843dd3af-3f2a-41b7-9727-90a7b153d34c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>7bbe0097-fbf1-4d7f-acdc-a6d6606f0faa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>YukJahitKeranjangAkunProfilPembelianKeluarSelesaikan pembayaran sebelumMinggu, 25 Juni 2023  22:07 WIBLoading...Silahkan akses link berikuthttps://simulator.sandbox.midtrans.com/gopay/partner/app/payment-pin?id=fd095c96-1a63-4627-b540-534d32fdf467© 2023 YukJahit. All rights reservedTwitterYouTubeInstagram</value>
      <webElementGuid>0a329f03-8470-4081-abc4-8166625a5a94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)</value>
      <webElementGuid>6884038c-174b-4fd0-9043-b5e4be19fb0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='root']</value>
      <webElementGuid>9bffffbf-9f38-46af-8bef-300fb774ccd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div</value>
      <webElementGuid>3240876c-c3d2-4abe-83c1-37d7f8bb782e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'root' and (text() = 'YukJahitKeranjangAkunProfilPembelianKeluarSelesaikan pembayaran sebelumMinggu, 25 Juni 2023  22:07 WIBLoading...Silahkan akses link berikuthttps://simulator.sandbox.midtrans.com/gopay/partner/app/payment-pin?id=fd095c96-1a63-4627-b540-534d32fdf467© 2023 YukJahit. All rights reservedTwitterYouTubeInstagram' or . = 'YukJahitKeranjangAkunProfilPembelianKeluarSelesaikan pembayaran sebelumMinggu, 25 Juni 2023  22:07 WIBLoading...Silahkan akses link berikuthttps://simulator.sandbox.midtrans.com/gopay/partner/app/payment-pin?id=fd095c96-1a63-4627-b540-534d32fdf467© 2023 YukJahit. All rights reservedTwitterYouTubeInstagram')]</value>
      <webElementGuid>5626b195-51a0-48a6-bf9c-749a72a804b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
