<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Kembali (modal)</name>
   <tag></tag>
   <elementGuidId>80c2d094-a3f0-4d90-a00d-c4f7e124acfc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-profile-modal-footer-close-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='edit-profile-modal-footer-close-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b8425d1e-aa4e-40d5-ba82-a709e1026708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>27821694-a4c0-4ae6-a32d-27cc4a4cb516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-button css-1681faw</value>
      <webElementGuid>15bdd5dc-f507-484f-9148-ba561b465c40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-profile-modal-footer-close-button</value>
      <webElementGuid>bc9e6240-c9c1-46a2-aaa7-c7db8c5f56c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tutup</value>
      <webElementGuid>7384b3ad-8980-406f-adf5-f559ef33dffc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-profile-modal-footer-close-button&quot;)</value>
      <webElementGuid>f5ca1289-b4fa-4754-90cf-9ec377bc570c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='edit-profile-modal-footer-close-button']</value>
      <webElementGuid>e014d540-ce6f-41ce-b7e5-80b5ccff1136</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat Lengkap'])[1]/following::button[1]</value>
      <webElementGuid>b5fe9108-5cbc-43db-8091-f31507b0560b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor HP'])[1]/following::button[1]</value>
      <webElementGuid>22585d6a-343d-4560-a295-0ad29bfc90fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ubah'])[1]/preceding::button[1]</value>
      <webElementGuid>2de59a4e-6dcf-4dca-b6dd-a7dfb0a449f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tutup']/parent::*</value>
      <webElementGuid>b6a41201-dad9-44e1-bbd1-2685ea59d418</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/button</value>
      <webElementGuid>216be7e6-6128-456a-b6a2-39af25f50f64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'edit-profile-modal-footer-close-button' and (text() = 'Batal' or . = 'Batal'')]</value>
      <webElementGuid>586ceff0-c93a-4718-b660-dbeb0c42215c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
