<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_phone</name>
   <tag></tag>
   <elementGuidId>90de92bc-123c-4f77-9073-5722099d5386</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='user-phone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#user-phone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>e065b2c9-e189-4195-ac98-220b0d43199d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-text css-0</value>
      <webElementGuid>5b1b531b-2c4b-4ecd-87b8-1eaa2a16e519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user-phone</value>
      <webElementGuid>9e91a012-4154-4e1c-88b3-f4a9fa677856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 08134489889</value>
      <webElementGuid>ce3a6474-ed9c-49f6-b3dc-dacff88bdcae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user-phone&quot;)</value>
      <webElementGuid>ddfab270-a8ce-43af-837a-dde36a1e156e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='user-phone']</value>
      <webElementGuid>7e2302f3-2656-4faf-8bd8-576246cf35d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div/div[2]/p[2]</value>
      <webElementGuid>7b5f8019-7665-45fe-a5a3-07e84ea35a28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Usery Tadd'])[1]/following::p[4]</value>
      <webElementGuid>7b153380-0d65-4254-bed5-9a3501e2765d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profil Saya'])[1]/following::p[4]</value>
      <webElementGuid>6fd88904-9c03-4814-9d3b-19bc6e2f7c21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ubah Data Profil'])[1]/preceding::p[3]</value>
      <webElementGuid>bf0311d3-20a7-45b8-9a47-d00648825c3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Twitter'])[1]/preceding::p[4]</value>
      <webElementGuid>e45be67b-d8c9-4534-b9d9-790b5b3381dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='08134489889']/parent::*</value>
      <webElementGuid>7d4db1de-5c3c-4b27-a3cc-ab6e2ec7ca7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p[2]</value>
      <webElementGuid>469d8537-ac8c-4d3c-96ba-49092d49e96f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'user-phone' and (text() = ' 08134489889' or . = ' 08134489889')]</value>
      <webElementGuid>9007a853-8935-48bc-b1f4-87465bbb886d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
