<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_YukJahit</name>
   <tag></tag>
   <elementGuidId>4a8477ae-3d8d-43ba-86e4-6dd98e485fe3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='logo-link']/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.chakra-text.css-10rv9l1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>e55da7dc-95d0-4113-93d5-e874522b9387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-text css-10rv9l1</value>
      <webElementGuid>2dd659cf-8ce1-4d77-bfbb-3e17967e3ae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>YukJahit</value>
      <webElementGuid>0a159757-4383-4566-8131-1e3c531e86a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logo-link&quot;)/h1[@class=&quot;chakra-text css-10rv9l1&quot;]</value>
      <webElementGuid>5aeda34f-df80-4721-9ad0-b5f56ec405ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='logo-link']/h1</value>
      <webElementGuid>0099f147-820b-4221-807d-fdb26d6faeb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[1]/preceding::h1[1]</value>
      <webElementGuid>3318fc7a-c5f8-4a44-a89d-73f35878b030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Yuk']/parent::*</value>
      <webElementGuid>22c83a54-7165-431e-b154-864b75f17986</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>5da10d58-ac49-4798-87fa-2dbcaf5bb401</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'YukJahit' or . = 'YukJahit')]</value>
      <webElementGuid>b4902b6c-9f72-4259-95c4-7832e4d556f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
