<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Daftar_chakra-image css-12mhnvv</name>
   <tag></tag>
   <elementGuidId>bc0ed7a0-26b2-4161-abed-b7fa615dd1c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='404-page']/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.chakra-image.css-12mhnvv</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>993b2318-1e8e-4f40-a5bd-f4da1ed2207e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>404</value>
      <webElementGuid>291b3939-ff0a-4adb-bc00-3a3e96680927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/404.jpg</value>
      <webElementGuid>1935d365-7864-4510-881e-328917dee6d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-image css-12mhnvv</value>
      <webElementGuid>35ca4b36-a58a-4927-bea9-5d02bdeccc06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;404-page&quot;)/div[@class=&quot;css-ibmrth&quot;]/img[@class=&quot;chakra-image css-12mhnvv&quot;]</value>
      <webElementGuid>9b5c8fea-6830-428a-8f09-ef5af57feec6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='404-page']/div/img</value>
      <webElementGuid>8764c2d3-08a2-485b-ad52-f41423a12d80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='404']</value>
      <webElementGuid>2459fc28-aa30-4d00-a062-7e641bf0c6b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>e45404bb-88b4-4f5b-9d5c-ef8765191d3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = '404' and @src = '/404.jpg']</value>
      <webElementGuid>b6ba1f5a-4b5d-4ef5-87dc-83f570cd55b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
