<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Daftar</name>
   <tag></tag>
   <elementGuidId>ddd26eb5-1179-499d-81bf-6048bcbd14c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nav-register-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='nav-register-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7c8a74d0-bf1f-4f9e-9971-25a13bb32a18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-button css-12a7g8u</value>
      <webElementGuid>e5f32cd5-48bc-4a7f-972f-ec35a78b0ab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-register-button</value>
      <webElementGuid>e892b0e2-e088-4e5e-b1f3-a74827e1c9af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/register</value>
      <webElementGuid>57749a01-7a6a-452a-ac45-83ee66a57a87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daftar</value>
      <webElementGuid>baf1c4f9-6c88-4212-a6b6-178cc2c50952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-register-button&quot;)</value>
      <webElementGuid>80f0853a-a05a-4cda-a192-b354814f5db7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='nav-register-button']</value>
      <webElementGuid>a045af2d-4fb4-45d0-916b-bf3262dc2ca0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/a[2]</value>
      <webElementGuid>ff20ddd4-ddb9-43fb-8e0f-a02e7aa00a99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Daftar')]</value>
      <webElementGuid>9fc1883f-d93d-45e4-8df8-91cb4ddbe422</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[1]/following::a[1]</value>
      <webElementGuid>2be860bc-032b-4d4d-be4b-06b6115777d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jahit'])[1]/following::a[2]</value>
      <webElementGuid>678dc615-b46f-4fc2-bb3f-a509ab865501</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jahit'])[2]/preceding::a[1]</value>
      <webElementGuid>6d9025c1-5101-4f8c-8e39-e7972edb353d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Daftar']/parent::*</value>
      <webElementGuid>6db6d56d-dd75-4b29-8c26-0788fd2063a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/register')]</value>
      <webElementGuid>31d73a1d-78b3-4c14-8b1d-1a87558c789c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>fb1c70af-f0f3-4968-9d64-7cc1b651aa8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'nav-register-button' and @href = '/register' and (text() = 'Daftar' or . = 'Daftar')]</value>
      <webElementGuid>970c0bc6-60b8-472a-a0b4-5e4d7f2cca4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
