<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Masuk</name>
   <tag></tag>
   <elementGuidId>08d16934-a334-4108-9041-8316c789d817</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/form/div/h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h2.chakra-text.css-1fqhvzd</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>538b6553-dfdb-469b-a251-4c62fe43876c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-text css-1fqhvzd</value>
      <webElementGuid>b0bee59f-7715-4f95-a3f0-ed436dd6e885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masuk</value>
      <webElementGuid>9d2d1432-7b37-471c-ac21-cdf881db40b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;chakra-container css-7wi6f6&quot;]/form[@class=&quot;chakra-stack css-dzysg8&quot;]/div[@class=&quot;chakra-stack css-17ulmjr&quot;]/h2[@class=&quot;chakra-text css-1fqhvzd&quot;]</value>
      <webElementGuid>3074fe5c-9e67-4ecf-845f-dbd05ad58200</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/form/div/h2</value>
      <webElementGuid>2057794e-b236-4cf1-88dc-059137e695b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jahit'])[2]/following::h2[1]</value>
      <webElementGuid>7c4136cc-dffd-4fc4-a08f-d5baa4d4af8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>3314ef21-c00c-434a-943c-c1186c6c636e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Masuk' or . = 'Masuk')]</value>
      <webElementGuid>c1775360-5117-4030-b125-eb08f92028c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
