<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_httpssimulator.sandbox.midtrans.comgopayp_c260c9</name>
   <tag></tag>
   <elementGuidId>14b4efda-cb58-43a5-903d-b22ce5a03ab2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='payment-link']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#payment-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1d79c732-d204-4df0-a6d9-94a7ab4c2b40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>7601ed5c-ef7f-4b2d-b1ae-4c6abbb4b958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener</value>
      <webElementGuid>bb6c5953-23b5-481c-bb9b-a06fda4ee16d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-link css-spn4bz</value>
      <webElementGuid>28222b25-b525-4504-8d7d-3bc77b35aa9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payment-link</value>
      <webElementGuid>d49fb2aa-c3ed-4e8f-8372-6434ec5b107b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://simulator.sandbox.midtrans.com/gopay/partner/app/payment-pin?id=c10e5361-ace6-441b-9d71-5c22b3220212</value>
      <webElementGuid>80be60dc-2f97-4bce-ace5-4c6d6f14c144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>https://simulator.sandbox.midtrans.com/gopay/partner/app/payment-pin?id=c10e5361-ace6-441b-9d71-5c22b3220212</value>
      <webElementGuid>f0124103-7d12-4fa3-b112-f9f8c1cfb972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-link&quot;)</value>
      <webElementGuid>3fe64d3a-ae93-42cf-8f6d-4343e93a6578</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='payment-link']</value>
      <webElementGuid>5080561d-0474-4b14-9a12-597f65e2a36f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div[2]/a</value>
      <webElementGuid>7571edda-787f-464c-b19c-17762edc2b55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'https://simulator.sandbox.midtrans.com/gopay/partner/app/payment-pin?id=c10e5361-ace6-441b-9d71-5c22b3220212')]</value>
      <webElementGuid>590f2dda-d36d-4dd8-bcfd-075e3b017ad3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Silahkan akses link berikut'])[1]/following::a[1]</value>
      <webElementGuid>f4782466-ac30-444a-a9c8-ac9221173caa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[1]/following::a[1]</value>
      <webElementGuid>f889c40e-843c-4536-bb04-2195d92f3334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Twitter'])[1]/preceding::a[1]</value>
      <webElementGuid>3dac6805-bab6-4d46-9b64-7a6e7df47280</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YouTube'])[1]/preceding::a[2]</value>
      <webElementGuid>51afd45a-efc2-4844-8b24-896b2b3a3af8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='https://simulator.sandbox.midtrans.com/gopay/partner/app/payment-pin?id=c10e5361-ace6-441b-9d71-5c22b3220212']/parent::*</value>
      <webElementGuid>2c45e2dc-7700-449c-84e9-4f198b77d39d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://simulator.sandbox.midtrans.com/gopay/partner/app/payment-pin?id=c10e5361-ace6-441b-9d71-5c22b3220212')]</value>
      <webElementGuid>dedab3d1-691e-41bf-b34a-bc951f0bd630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/a</value>
      <webElementGuid>a2bfd81c-2ef0-482c-8c31-59b28827b831</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'payment-link' and @href = 'https://simulator.sandbox.midtrans.com/gopay/partner/app/payment-pin?id=c10e5361-ace6-441b-9d71-5c22b3220212' and (text() = 'https://simulator.sandbox.midtrans.com/gopay/partner/app/payment-pin?id=c10e5361-ace6-441b-9d71-5c22b3220212' or . = 'https://simulator.sandbox.midtrans.com/gopay/partner/app/payment-pin?id=c10e5361-ace6-441b-9d71-5c22b3220212')]</value>
      <webElementGuid>65581fc6-b33d-4f05-905c-fa6de0fc870a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
