<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Jumlah-</name>
   <tag></tag>
   <elementGuidId>20c40503-754d-4f66-af0e-9d76ab32d4e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/form/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-1velzb3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a9339207-5380-47e0-8d52-592ac42fd941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1velzb3</value>
      <webElementGuid>814c4434-09bf-4004-9414-5601b3fc48bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jumlah:-+</value>
      <webElementGuid>1189834d-83ea-4478-821c-cbb7d9f894b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;chakra-container css-3fg9fx&quot;]/form[@class=&quot;css-bex158&quot;]/div[@class=&quot;css-1005ark&quot;]/div[@class=&quot;css-1velzb3&quot;]</value>
      <webElementGuid>a44e2431-173d-49de-b5f3-11a85ebb815a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/form/div/div</value>
      <webElementGuid>9ee63ebb-6d37-4978-9841-8892b5ac946a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kaos Abu Polos'])[2]/following::div[1]</value>
      <webElementGuid>2c9ad7b4-c3e8-460d-9030-1f63458d7477</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kaos Abu Polos'])[1]/following::div[2]</value>
      <webElementGuid>dbb4e0a0-fec1-4f38-b356-a80431cbd886</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/div/div</value>
      <webElementGuid>c972d08c-2e0b-4938-a304-ca76fb7f6455</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Jumlah:-+' or . = 'Jumlah:-+')]</value>
      <webElementGuid>507dfaa8-d08b-41bf-83f5-18095ead9a20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
